server:
  port:8888
spring:
  application:
    name: selenium-splider
  datasource:
    url: jdbc:mysql://localhost:3306/qzone_splider?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver