spring:
  application:
    name: selenium-splider
  datasource:
    url: jdbc:mysql://localhost:3306/qzone_spider?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: muyahai
    password: muyahai
    listener:
      simple:
        acknowledge-mode: none
server:
  port: 8888
logging:
  level:
    com.cn.selenium.spider.mapper : debug
